#112/loading favourites
enBloc-org/arebyte-plugin-v4 pull request #126
Opened 2024-11-11 09:14 UTC by camelPhonso

# Description

**Closes #112**

Creates a new higher order component that wraps any children given to it with the logic to handle a loading state.

I've applied this new component to both the `Favourites` and the `Explore` page as they both handle similar loading of a lot of data. This component flashes the logo in assets while we load because I thought that would be a more personalised look than just adding a spinner - but that's very much under question I think.

### Files changed

- `components/WithLoading/` - new component plus styling
- `FavouritesPage.tsx` and `ExplorePage.tsx` - import the new `WithLoading` component and wrap the elements displaying fetched data in it

### UI changes

The pages look exactly the same, but if you throttle the app you'll see the arebyte logo flashing for a few seconds before the data is loaded

### Changes to Documentation

n/a

# Tests

n/a - no changes to the logic in the code

2024-11-11 11:03 UTC, nichgalzin requested changes

2024-11-11 11:03 UTC, nichgalzin commented on src/components/WithLoading/WithLoading.tsx
> +    return <img className="with-loading__loading" src={logo} />
As we discussed, lets wrap this in a div with flex center in whatever layout it's in.

2024-11-11 11:35 UTC, camelPhonso commented on src/components/WithLoading/WithLoading.tsx
> +    return <img className="with-loading__loading" src={logo} />
schön gut 👌 

I've pushed this edit in a new commit

2024-11-12 12:14 UTC, nichgalzin approved these changes
Great stuff

2024-11-12 12:14 UTC, merged