#21/testing
enBloc-org/arebyte-plugin-v4 pull request #24
Opened 2024-09-24 14:53 UTC by camelPhonso

# Description

**Closes #21**  

Sets up jest for unit testing and creates an example file testing the handler for `updateMessage` method on our context.

### Files changed

- `jest.config.mjs`, `tsconfig.json`, `pnpm-lock.yaml`, `package.json` - installed new dependencies and updated configurations to allow jest to play nicely with our codebase
- `.husky/pre-commit` - added a check to our pre-commit hook that runs any tests associated with any files we have edited in that commit
- `background/index.ts` - renamed `background.ts` in accordance with @plasmo/messaging documentation
- `set_context.test.ts` - example unit test for our `set_context` handler

### UI changes

n/a

### Changes to Documentation

 - `README.md` and `TESTING.md` - updated with guidance on tests

# Tests

```bash
pnpm test // for all tests

pnpm test:changed // for any tests associated with files edited since the last commit

```

2024-09-24 16:28 UTC, camelPhonso commented
Replaced the example test with a test for the new store method after merging dev ✨

2024-09-24 17:39 UTC, nichgalzin requested changes
Mind removing the updateMessage utils? Or if we want to fix it make it a generic message handler function perhaps? Any, it has a type error that showing in the problems log. Thank youuuuuuu!

2024-09-24 17:39 UTC, nichgalzin commented on src/background/messages/fetchCurrentProject.test.ts
> +  beforeEach(() => {
My IDE is saying that the import call is missing for beforeEach, which is strange as the tests still pass without it. But it stops complaining when you add it the the @jest/globals import statement.

2024-09-25 09:49 UTC, camelPhonso commented on src/background/messages/fetchCurrentProject.test.ts
> +  beforeEach(() => {
added that import now 👍

2024-09-27 11:49 UTC, nichgalzin approved these changes
Great stuff

2024-09-27 11:49 UTC, merged